adding OutPutPath

diff --git a/.github/workflows/create-any-build.yml b/.github/workflows/create-any-build.yml
--- a/.github/workflows/create-any-build.yml
+++ b/.github/workflows/create-any-build.yml
@@ -64,7 +64,7 @@ jobs:
       # ********** Create the RELEASE and DEBUG Builds **********
       - name: Create RELEASE Build        
         run: |
-          MSBuild.exe ${{ env.SOLUTION_FILE_FULL_PATH }} /t:Build /p:Configuration=Release
+          MSBuild.exe ${{ env.SOLUTION_FILE_FULL_PATH }} /t:Build /p:Configuration=Release /p:OutPutPath=bin\Release
           $exitCode = $LASTEXITCODE
           echo "ErrorCode == $exitCode End of line"
           if ( $exitCode -ne 0 )
@@ -73,42 +73,28 @@ jobs:
             exit $exitCode # Exit the workflow with the same error code
           }
           
-      # - name: Create DEBUG Build        
-      #   run: |
-      #     MSBuild.exe ${{ env.SOLUTION_FILE_FULL_PATH }} /t:Build /p:Configuration=Debug
-      #     $exitCode = $LASTEXITCODE
-      #     if ( $exitCode -ne 0 )
-      #     {
-      #       echo "DEBUG build failed with exit code $exitCode"
-      #       exit $exitCode # Exit the workflow with the same error code
-      #     }
+      - name: Create DEBUG Build        
+        run: |
+          MSBuild.exe ${{ env.SOLUTION_FILE_FULL_PATH }} /t:Build /p:Configuration=Debug /p:OutPutPath=bin\Debug
+          $exitCode = $LASTEXITCODE
+          if ( $exitCode -ne 0 )
+          {
+            echo "DEBUG build failed with exit code $exitCode"
+            exit $exitCode # Exit the workflow with the same error code
+          }
 
 
       # ********** Find and store the full RELEASE & DEBUG build paths **********
-      # - name: Find and store the full RELEASE build path
-      #   run: |
-      #     $rel_build_path = cmd.exe /c dir /s /b /a-d | findstr /i "\\bin\\release\\.*\.exe$"
-      #     $rel_build_path = Split-Path $rel_build_path -Parent
-      #     echo "RELEASE_BUILD_PATH=$rel_build_path" >> $env:GITHUB_ENV
-      #     echo $rel_build_path
-
       - name: Find and store the full RELEASE build path
         run: |
-          $rel_build_path = cmd.exe /c dir /s /b /a-d | findstr /i "\\bin\\\(x64\\\)?release\\.*\.exe$"
+          $rel_build_path = cmd.exe /c dir /s /b /a-d | findstr /i "\\bin\\release\\.*\.exe$"
           $rel_build_path = Split-Path $rel_build_path -Parent
           echo "RELEASE_BUILD_PATH=$rel_build_path" >> $env:GITHUB_ENV
           echo $rel_build_path
 
-        # - name: Find and store the full DEBUG build path
-        #   run: |
-        #     $dbg_build_path = cmd.exe /c dir /s /b /a-d | findstr /i "\\bin\\debug\\.*\.exe$"
-        #     $dbg_build_path = Split-Path $dbg_build_path -Parent
-        #     echo "DEBUG_BUILD_PATH=$dbg_build_path" >> $env:GITHUB_ENV
-        #     echo $dbg_build_path
-
       - name: Find and store the full DEBUG build path
         run: |
-          $dbg_build_path = cmd.exe /c dir /s /b /a-d | findstr /i "\\bin\\\(x64\\\)?debug\\.*\.exe$"
+          $dbg_build_path = cmd.exe /c dir /s /b /a-d | findstr /i "\\bin\\debug\\.*\.exe$"
           $dbg_build_path = Split-Path $dbg_build_path -Parent
           echo "DEBUG_BUILD_PATH=$dbg_build_path" >> $env:GITHUB_ENV
           echo $dbg_build_path
